#ifndef		__GAIA_INSTANCE_CREATOR_IMPL_H__
#define		__GAIA_INSTANCE_CREATOR_IMPL_H__

namespace GAIA
{
	namespace FWORK
	{
		namespace INSTCREATOR
		{
		#define GAIA_INSTCREATOR(cid, type) \
			class cid##_InstanceCreator : public GAIA::FWORK::INSTCREATOR::InstanceCreator\
			{\
			public:\
				virtual GAIA::FWORK::Instance* Create(){return new type;}\
			};

			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_GATEWAYMEM, GAIA::DATATRAFFIC::GatewayMem);
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_GATEWAYSHAREMEM, GAIA::DATATRAFFIC::GatewayShareMem);
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_GATEWAYFILE, GAIA::DATATRAFFIC::GatewayFile);
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_ROUTEMEM, GAIA::DATATRAFFIC::RouteMem);
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_ROUTENET, GAIA::DATATRAFFIC::RouteNet);
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_TRANSMISSIONIDM, GAIA::DATATRAFFIC::TransmissionIDM);
			GAIA_INSTCREATOR(CLSID_IO_FILEIO, GAIA::IO::FileIO);
			GAIA_INSTCREATOR(CLSID_IO_MEMIO, GAIA::IO::MemIO);
			GAIA_INSTCREATOR(CLSID_IO_SCREENIO, GAIA::IO::ScreenIO);
			GAIA_INSTCREATOR(CLSID_SERIALIZER, GAIA::SERIALIZER::Serializer);
			GAIA_INSTCREATOR(CLSID_UI_CANVAS, GAIA::UI::Canvas);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW, GAIA::RENDER::Render2DDDraw);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS, GAIA::RENDER::Render2DGDIPlus);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9, GAIA::RENDER::Render3DDX9);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10, GAIA::RENDER::Render3DDX10);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11, GAIA::RENDER::Render3DDX11);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1, GAIA::RENDER::Render3DGL1);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2, GAIA::RENDER::Render3DGL2);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3, GAIA::RENDER::Render3DGL3);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1, GAIA::RENDER::Render3DGLES1);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2, GAIA::RENDER::Render3DGLES2);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3, GAIA::RENDER::Render3DGLES3);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_PEN, GAIA::RENDER::Render2DDDraw::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_PEN, GAIA::RENDER::Render2DGDIPlus::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_PEN, GAIA::RENDER::Render3DDX9::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_PEN, GAIA::RENDER::Render3DDX10::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_PEN, GAIA::RENDER::Render3DDX11::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_PEN, GAIA::RENDER::Render3DGL1::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_PEN, GAIA::RENDER::Render3DGL2::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_PEN, GAIA::RENDER::Render3DGL3::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_PEN, GAIA::RENDER::Render3DGLES1::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_PEN, GAIA::RENDER::Render3DGLES2::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_PEN, GAIA::RENDER::Render3DGLES3::Pen);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_BRUSH, GAIA::RENDER::Render2DDDraw::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_BRUSH, GAIA::RENDER::Render2DGDIPlus::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_BRUSH, GAIA::RENDER::Render3DDX9::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_BRUSH, GAIA::RENDER::Render3DDX10::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_BRUSH, GAIA::RENDER::Render3DDX11::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_BRUSH, GAIA::RENDER::Render3DGL1::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_BRUSH, GAIA::RENDER::Render3DGL2::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_BRUSH, GAIA::RENDER::Render3DGL3::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_BRUSH, GAIA::RENDER::Render3DGLES1::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_BRUSH, GAIA::RENDER::Render3DGLES2::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_BRUSH, GAIA::RENDER::Render3DGLES3::Brush);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_FONTPAINTER, GAIA::RENDER::Render2DDDraw::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_FONTPAINTER, GAIA::RENDER::Render2DGDIPlus::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_FONTPAINTER, GAIA::RENDER::Render3DDX9::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_FONTPAINTER, GAIA::RENDER::Render3DDX10::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_FONTPAINTER, GAIA::RENDER::Render3DDX11::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_FONTPAINTER, GAIA::RENDER::Render3DGL1::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_FONTPAINTER, GAIA::RENDER::Render3DGL2::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_FONTPAINTER, GAIA::RENDER::Render3DGL3::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_FONTPAINTER, GAIA::RENDER::Render3DGLES1::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_FONTPAINTER, GAIA::RENDER::Render3DGLES2::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_FONTPAINTER, GAIA::RENDER::Render3DGLES3::FontPainter);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_FONTFAMILY, GAIA::RENDER::Render2DDDraw::FontPainterFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_FONTFAMILY, GAIA::RENDER::Render2DGDIPlus::FontPainterFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_FONTFAMILY, GAIA::RENDER::Render3DDX9::FontPainterFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_FONTFAMILY, GAIA::RENDER::Render3DDX10::FontPainterFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_FONTFAMILY, GAIA::RENDER::Render3DDX11::FontPainterFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_FONTFAMILY, GAIA::RENDER::Render3DGL1::FontPainterFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_FONTFAMILY, GAIA::RENDER::Render3DGL2::FontPainterFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_FONTFAMILY, GAIA::RENDER::Render3DGL3::FontPainterFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_FONTFAMILY, GAIA::RENDER::Render3DGLES1::FontPainterFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_FONTFAMILY, GAIA::RENDER::Render3DGLES2::FontPainterFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_FONTFAMILY, GAIA::RENDER::Render3DGLES3::FontPainterFamily);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_FONTFORMAT, GAIA::RENDER::Render2DDDraw::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_FONTFORMAT, GAIA::RENDER::Render2DGDIPlus::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_FONTFORMAT, GAIA::RENDER::Render3DDX9::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_FONTFORMAT, GAIA::RENDER::Render3DDX10::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_FONTFORMAT, GAIA::RENDER::Render3DDX11::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_FONTFORMAT, GAIA::RENDER::Render3DGL1::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_FONTFORMAT, GAIA::RENDER::Render3DGL2::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_FONTFORMAT, GAIA::RENDER::Render3DGL3::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_FONTFORMAT, GAIA::RENDER::Render3DGLES1::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_FONTFORMAT, GAIA::RENDER::Render3DGLES2::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_FONTFORMAT, GAIA::RENDER::Render3DGLES3::FontFormat);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_TARGET, GAIA::RENDER::Render2DDDraw::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_TARGET, GAIA::RENDER::Render2DGDIPlus::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_TARGET, GAIA::RENDER::Render3DDX9::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_TARGET, GAIA::RENDER::Render3DDX10::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_TARGET, GAIA::RENDER::Render3DDX11::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_TARGET, GAIA::RENDER::Render3DGL1::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_TARGET, GAIA::RENDER::Render3DGL2::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_TARGET, GAIA::RENDER::Render3DGL3::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_TARGET, GAIA::RENDER::Render3DGLES1::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_TARGET, GAIA::RENDER::Render3DGLES2::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_TARGET, GAIA::RENDER::Render3DGLES3::Target);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_SHADER, GAIA::RENDER::Render2DDDraw::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_SHADER, GAIA::RENDER::Render2DGDIPlus::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_SHADER, GAIA::RENDER::Render3DDX9::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_SHADER, GAIA::RENDER::Render3DDX10::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_SHADER, GAIA::RENDER::Render3DDX11::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_SHADER, GAIA::RENDER::Render3DGL1::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_SHADER, GAIA::RENDER::Render3DGL2::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_SHADER, GAIA::RENDER::Render3DGL3::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_SHADER, GAIA::RENDER::Render3DGLES1::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_SHADER, GAIA::RENDER::Render3DGLES2::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_SHADER, GAIA::RENDER::Render3DGLES3::Shader);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_TEXTURE, GAIA::RENDER::Render2DDDraw::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_TEXTURE, GAIA::RENDER::Render2DGDIPlus::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_TEXTURE, GAIA::RENDER::Render3DDX9::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_TEXTURE, GAIA::RENDER::Render3DDX10::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_TEXTURE, GAIA::RENDER::Render3DDX11::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_TEXTURE, GAIA::RENDER::Render3DGL1::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_TEXTURE, GAIA::RENDER::Render3DGL2::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_TEXTURE, GAIA::RENDER::Render3DGL3::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_TEXTURE, GAIA::RENDER::Render3DGLES1::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_TEXTURE, GAIA::RENDER::Render3DGLES2::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_TEXTURE, GAIA::RENDER::Render3DGLES3::Texture);

			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_VERTEXDECLARATION, GAIA::RENDER::Render3DDX9::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_VERTEXDECLARATION, GAIA::RENDER::Render3DDX10::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_VERTEXDECLARATION, GAIA::RENDER::Render3DDX11::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_VERTEXDECLARATION, GAIA::RENDER::Render3DGL1::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_VERTEXDECLARATION, GAIA::RENDER::Render3DGL2::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_VERTEXDECLARATION, GAIA::RENDER::Render3DGL3::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_VERTEXDECLARATION, GAIA::RENDER::Render3DGLES1::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_VERTEXDECLARATION, GAIA::RENDER::Render3DGLES2::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_VERTEXDECLARATION, GAIA::RENDER::Render3DGLES3::VertexDeclaration);

			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_INDEXBUFFER, GAIA::RENDER::Render3DDX9::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_INDEXBUFFER, GAIA::RENDER::Render3DDX10::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_INDEXBUFFER, GAIA::RENDER::Render3DDX11::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_INDEXBUFFER, GAIA::RENDER::Render3DGL1::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_INDEXBUFFER, GAIA::RENDER::Render3DGL2::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_INDEXBUFFER, GAIA::RENDER::Render3DGL3::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_INDEXBUFFER, GAIA::RENDER::Render3DGLES1::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_INDEXBUFFER, GAIA::RENDER::Render3DGLES2::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_INDEXBUFFER, GAIA::RENDER::Render3DGLES3::IndexBuffer);

			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_VERTEXBUFFER, GAIA::RENDER::Render3DDX9::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_VERTEXBUFFER, GAIA::RENDER::Render3DDX10::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_VERTEXBUFFER, GAIA::RENDER::Render3DDX11::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_VERTEXBUFFER, GAIA::RENDER::Render3DGL1::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_VERTEXBUFFER, GAIA::RENDER::Render3DGL2::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_VERTEXBUFFER, GAIA::RENDER::Render3DGL3::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_VERTEXBUFFER, GAIA::RENDER::Render3DGLES1::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_VERTEXBUFFER, GAIA::RENDER::Render3DGLES2::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_VERTEXBUFFER, GAIA::RENDER::Render3DGLES3::VertexBuffer);
		};
	};
};

#endif