#ifndef		__GAIA_FACTORY_IMPL_H__
#define		__GAIA_FACTORY_IMPL_H__

namespace GAIA
{
	namespace FWORK
	{
		GINL Instance* GAIA::FWORK::Factory::CreateInstance(const ClsID& cid, GAIA::GVOID* pParameter)
		{
			if(cid.IsInvalid())
				return GNIL;
			Instance* pRet = GNIL;
			if(GAIA::ALWAYSFALSE){}

			/* Data traffic. */
			else if(cid == GAIA::FWORK::CLSID_DATATRAFFIC_GATEWAYMEM)
				pRet = new GAIA::DATATRAFFIC::GatewayMem;
			else if(cid == GAIA::FWORK::CLSID_DATATRAFFIC_GATEWAYSHAREMEM)
				pRet = new GAIA::DATATRAFFIC::GatewayShareMem;
			else if(cid == GAIA::FWORK::CLSID_DATATRAFFIC_GATEWAYFILE)
				pRet = new GAIA::DATATRAFFIC::GatewayFile;
			else if(cid == GAIA::FWORK::CLSID_DATATRAFFIC_ROUTEMEM)
				pRet = new GAIA::DATATRAFFIC::RouteMem;
			else if(cid == GAIA::FWORK::CLSID_DATATRAFFIC_ROUTENET)
				pRet = new GAIA::DATATRAFFIC::RouteNet;
			else if(cid == GAIA::FWORK::CLSID_DATATRAFFIC_TRANSMISSIONIDM)
				pRet = new GAIA::DATATRAFFIC::TransmissionIDM;

			/* IO. */
			else if(cid == GAIA::FWORK::CLSID_IO_FILEIO)
				pRet = new GAIA::IO::FileIO;
			else if(cid == GAIA::FWORK::CLSID_IO_MEMIO)
				pRet = new GAIA::IO::MemIO;
			else if(cid == GAIA::FWORK::CLSID_IO_SCREENIO)
				pRet = new GAIA::IO::ScreenIO;

			/* Serializer. */
			else if(cid == GAIA::FWORK::CLSID_SERIALIZER)
				pRet = new GAIA::SERIALIZER::Serializer;

			/* UI. */
			else if(cid == GAIA::FWORK::CLSID_UI_CANVAS)
				pRet = new GAIA::UI::Canvas;

			/* Render. */
			else if(cid == GAIA::FWORK::CLSID_RENDER_2D_DDRAW)
				pRet = new GAIA::RENDER::Render2DDDraw;
			else if(cid == GAIA::FWORK::CLSID_RENDER_2D_GDIPLUS)
				pRet = new GAIA::RENDER::Render2DGDIPlus;
			else if(cid == GAIA::FWORK::CLSID_RENDER_3D_DX9)
				pRet = new GAIA::RENDER::Render3DDX9;
			else if(cid == GAIA::FWORK::CLSID_RENDER_3D_DX10)
				pRet = new GAIA::RENDER::Render3DDX10;
			else if(cid == GAIA::FWORK::CLSID_RENDER_3D_DX11)
				pRet = new GAIA::RENDER::Render3DDX11;
			else if(cid == GAIA::FWORK::CLSID_RENDER_3D_GL1)
				pRet = new GAIA::RENDER::Render3DGL1;
			else if(cid == GAIA::FWORK::CLSID_RENDER_3D_GL2)
				pRet = new GAIA::RENDER::Render3DGL2;
			else if(cid == GAIA::FWORK::CLSID_RENDER_3D_GL3)
				pRet = new GAIA::RENDER::Render3DGL3;
			else if(cid == GAIA::FWORK::CLSID_RENDER_3D_GLES1)
				pRet = new GAIA::RENDER::Render3DGLES1;
			else if(cid == GAIA::FWORK::CLSID_RENDER_3D_GLES2)
				pRet = new GAIA::RENDER::Render3DGLES2;
			else if(cid == GAIA::FWORK::CLSID_RENDER_3D_GLES3)
				pRet = new GAIA::RENDER::Render3DGLES3;

			if(pRet == GNIL)
			{
				for(LIST_CREATECALLBACK::_sizetype x = 0; x < m_listCreateCB.size(); ++x)
				{
					FactoryCreateCallBack* pCallBack = m_listCreateCB[x];
					pRet = pCallBack->Create(this, cid);
					if(pRet != GNIL)
						break;
				}
			}

			if(pRet != GNIL)
			{
				pRet->SetFactory(this);
				if(!pRet->InstanceBegin(pParameter))
				{
					pRet->Release();
					pRet = GNIL;
				}
			}

			return pRet;
		}
		GINL Instance* GAIA::FWORK::Factory::RequestInstance(const ClsID& cid, GAIA::GVOID* pParameter)
		{
			return GNIL;
		}
		GINL GAIA::GVOID GAIA::FWORK::Factory::GenerateCreator()
		{
			GAIA_AST(!this->IsBeginRegistClsID());
			if(this->IsBeginRegistClsID())
				return;

#define GAIA_MAPPING_CREATEINSTANCEPROC(declcid)\
			{\
				CLSIDNODE finder;\
				finder.cid = declcid;\
				__ClsIDListType::_sizetype index = m_RegClsIDList.search(finder);\
				if(index != GINVALID)\
					m_RegClsIDList[index].proc = GAIA::FWORK::INSTCREATOR::declcid##_PROC;\
			}

			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_DATATRAFFIC_GATEWAYMEM);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_DATATRAFFIC_GATEWAYSHAREMEM);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_DATATRAFFIC_GATEWAYFILE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_DATATRAFFIC_ROUTEMEM);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_DATATRAFFIC_ROUTENET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_DATATRAFFIC_TRANSMISSIONIDM);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_IO_FILEIO);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_IO_MEMIO);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_IO_SCREENIO);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_SERIALIZER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_UI_CANVAS);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_DDRAW);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_GDIPLUS);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_DDRAW_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_GDIPLUS_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_PEN);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_DDRAW_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_GDIPLUS_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_BRUSH);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_DDRAW_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_GDIPLUS_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_FONTPAINTER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_DDRAW_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_GDIPLUS_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_FONTFAMILY);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_DDRAW_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_GDIPLUS_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_FONTFORMAT);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_DDRAW_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_GDIPLUS_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_TARGET);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_DDRAW_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_GDIPLUS_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_SHADER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_DDRAW_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_2D_GDIPLUS_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_TEXTURE);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_VERTEXDECLARATION);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_VERTEXDECLARATION);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_VERTEXDECLARATION);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_VERTEXDECLARATION);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_VERTEXDECLARATION);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_VERTEXDECLARATION);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_VERTEXDECLARATION);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_VERTEXDECLARATION);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_VERTEXDECLARATION);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_INDEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_INDEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_INDEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_INDEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_INDEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_INDEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_INDEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_INDEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_INDEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX9_VERTEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX10_VERTEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_DX11_VERTEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL1_VERTEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL2_VERTEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GL3_VERTEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES1_VERTEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES2_VERTEXBUFFER);
			GAIA_MAPPING_CREATEINSTANCEPROC(CLSID_RENDER_3D_GLES3_VERTEXBUFFER);
		}
	};
};

#endif