#ifndef		__GAIA_FRAMEWORK_INSTANCE_CREATOR_IMPL_H__
#define		__GAIA_FRAMEWORK_INSTANCE_CREATOR_IMPL_H__

namespace GAIA
{
	namespace FWORK
	{
		namespace INSTCREATOR
		{
		#define GAIA_INSTCREATOR(cid, type) static GAIA::FWORK::Instance* cid##_PROC(){return new type;}

			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_GATEWAYMEM, GAIA::DATATRAFFIC::GatewayMem);
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_GATEWAYSHAREMEM, GAIA::DATATRAFFIC::GatewayShareMem);
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_GATEWAYFILE, GAIA::DATATRAFFIC::GatewayFile);
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_ROUTEMEM, GAIA::DATATRAFFIC::RouteMem);
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_ROUTENET, GAIA::DATATRAFFIC::RouteNet);
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_TRANSMISSIONIDM, GAIA::DATATRAFFIC::TransmissionIDM);

			GAIA_INSTCREATOR(CLSID_IO_FILEIO, GAIA::IO::FileIO);
			GAIA_INSTCREATOR(CLSID_IO_MEMIO, GAIA::IO::MemIO);
			GAIA_INSTCREATOR(CLSID_IO_SCREENIO, GAIA::IO::ScreenIO);

			GAIA_INSTCREATOR(CLSID_SERIALIZER, GAIA::SERIALIZER::Serializer);

			GAIA_INSTCREATOR(CLSID_UI_CANVAS, GAIA::UI::Canvas);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW, GAIA::RENDER::Render2DDDraw);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS, GAIA::RENDER::Render2DGDIPlus);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9, GAIA::RENDER::Render3DDX9);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10, GAIA::RENDER::Render3DDX10);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11, GAIA::RENDER::Render3DDX11);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1, GAIA::RENDER::Render3DGL1);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2, GAIA::RENDER::Render3DGL2);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3, GAIA::RENDER::Render3DGL3);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1, GAIA::RENDER::Render3DGLES1);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2, GAIA::RENDER::Render3DGLES2);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3, GAIA::RENDER::Render3DGLES3);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_PEN, GAIA::RENDER::Render2DDDraw::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_PEN, GAIA::RENDER::Render2DGDIPlus::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_PEN, GAIA::RENDER::Render3DDX9::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_PEN, GAIA::RENDER::Render3DDX10::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_PEN, GAIA::RENDER::Render3DDX11::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_PEN, GAIA::RENDER::Render3DGL1::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_PEN, GAIA::RENDER::Render3DGL2::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_PEN, GAIA::RENDER::Render3DGL3::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_PEN, GAIA::RENDER::Render3DGLES1::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_PEN, GAIA::RENDER::Render3DGLES2::Pen);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_PEN, GAIA::RENDER::Render3DGLES3::Pen);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_BRUSH, GAIA::RENDER::Render2DDDraw::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_BRUSH, GAIA::RENDER::Render2DGDIPlus::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_BRUSH, GAIA::RENDER::Render3DDX9::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_BRUSH, GAIA::RENDER::Render3DDX10::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_BRUSH, GAIA::RENDER::Render3DDX11::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_BRUSH, GAIA::RENDER::Render3DGL1::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_BRUSH, GAIA::RENDER::Render3DGL2::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_BRUSH, GAIA::RENDER::Render3DGL3::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_BRUSH, GAIA::RENDER::Render3DGLES1::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_BRUSH, GAIA::RENDER::Render3DGLES2::Brush);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_BRUSH, GAIA::RENDER::Render3DGLES3::Brush);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_FONTPAINTER, GAIA::RENDER::Render2DDDraw::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_FONTPAINTER, GAIA::RENDER::Render2DGDIPlus::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_FONTPAINTER, GAIA::RENDER::Render3DDX9::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_FONTPAINTER, GAIA::RENDER::Render3DDX10::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_FONTPAINTER, GAIA::RENDER::Render3DDX11::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_FONTPAINTER, GAIA::RENDER::Render3DGL1::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_FONTPAINTER, GAIA::RENDER::Render3DGL2::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_FONTPAINTER, GAIA::RENDER::Render3DGL3::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_FONTPAINTER, GAIA::RENDER::Render3DGLES1::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_FONTPAINTER, GAIA::RENDER::Render3DGLES2::FontPainter);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_FONTPAINTER, GAIA::RENDER::Render3DGLES3::FontPainter);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_FONTFAMILY, GAIA::RENDER::Render2DDDraw::FontFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_FONTFAMILY, GAIA::RENDER::Render2DGDIPlus::FontFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_FONTFAMILY, GAIA::RENDER::Render3DDX9::FontFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_FONTFAMILY, GAIA::RENDER::Render3DDX10::FontFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_FONTFAMILY, GAIA::RENDER::Render3DDX11::FontFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_FONTFAMILY, GAIA::RENDER::Render3DGL1::FontFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_FONTFAMILY, GAIA::RENDER::Render3DGL2::FontFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_FONTFAMILY, GAIA::RENDER::Render3DGL3::FontFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_FONTFAMILY, GAIA::RENDER::Render3DGLES1::FontFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_FONTFAMILY, GAIA::RENDER::Render3DGLES2::FontFamily);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_FONTFAMILY, GAIA::RENDER::Render3DGLES3::FontFamily);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_FONTFORMAT, GAIA::RENDER::Render2DDDraw::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_FONTFORMAT, GAIA::RENDER::Render2DGDIPlus::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_FONTFORMAT, GAIA::RENDER::Render3DDX9::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_FONTFORMAT, GAIA::RENDER::Render3DDX10::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_FONTFORMAT, GAIA::RENDER::Render3DDX11::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_FONTFORMAT, GAIA::RENDER::Render3DGL1::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_FONTFORMAT, GAIA::RENDER::Render3DGL2::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_FONTFORMAT, GAIA::RENDER::Render3DGL3::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_FONTFORMAT, GAIA::RENDER::Render3DGLES1::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_FONTFORMAT, GAIA::RENDER::Render3DGLES2::FontFormat);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_FONTFORMAT, GAIA::RENDER::Render3DGLES3::FontFormat);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_TARGET, GAIA::RENDER::Render2DDDraw::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_TARGET, GAIA::RENDER::Render2DGDIPlus::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_TARGET, GAIA::RENDER::Render3DDX9::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_TARGET, GAIA::RENDER::Render3DDX10::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_TARGET, GAIA::RENDER::Render3DDX11::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_TARGET, GAIA::RENDER::Render3DGL1::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_TARGET, GAIA::RENDER::Render3DGL2::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_TARGET, GAIA::RENDER::Render3DGL3::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_TARGET, GAIA::RENDER::Render3DGLES1::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_TARGET, GAIA::RENDER::Render3DGLES2::Target);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_TARGET, GAIA::RENDER::Render3DGLES3::Target);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_SHADER, GAIA::RENDER::Render2DDDraw::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_SHADER, GAIA::RENDER::Render2DGDIPlus::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_SHADER, GAIA::RENDER::Render3DDX9::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_SHADER, GAIA::RENDER::Render3DDX10::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_SHADER, GAIA::RENDER::Render3DDX11::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_SHADER, GAIA::RENDER::Render3DGL1::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_SHADER, GAIA::RENDER::Render3DGL2::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_SHADER, GAIA::RENDER::Render3DGL3::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_SHADER, GAIA::RENDER::Render3DGLES1::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_SHADER, GAIA::RENDER::Render3DGLES2::Shader);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_SHADER, GAIA::RENDER::Render3DGLES3::Shader);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_TEXTURE, GAIA::RENDER::Render2DDDraw::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_TEXTURE, GAIA::RENDER::Render2DGDIPlus::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_TEXTURE, GAIA::RENDER::Render3DDX9::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_TEXTURE, GAIA::RENDER::Render3DDX10::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_TEXTURE, GAIA::RENDER::Render3DDX11::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_TEXTURE, GAIA::RENDER::Render3DGL1::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_TEXTURE, GAIA::RENDER::Render3DGL2::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_TEXTURE, GAIA::RENDER::Render3DGL3::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_TEXTURE, GAIA::RENDER::Render3DGLES1::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_TEXTURE, GAIA::RENDER::Render3DGLES2::Texture);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_TEXTURE, GAIA::RENDER::Render3DGLES3::Texture);

			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_VERTEXDECLARATION, GAIA::RENDER::Render3DDX9::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_VERTEXDECLARATION, GAIA::RENDER::Render3DDX10::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_VERTEXDECLARATION, GAIA::RENDER::Render3DDX11::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_VERTEXDECLARATION, GAIA::RENDER::Render3DGL1::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_VERTEXDECLARATION, GAIA::RENDER::Render3DGL2::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_VERTEXDECLARATION, GAIA::RENDER::Render3DGL3::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_VERTEXDECLARATION, GAIA::RENDER::Render3DGLES1::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_VERTEXDECLARATION, GAIA::RENDER::Render3DGLES2::VertexDeclaration);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_VERTEXDECLARATION, GAIA::RENDER::Render3DGLES3::VertexDeclaration);

			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_INDEXBUFFER, GAIA::RENDER::Render3DDX9::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_INDEXBUFFER, GAIA::RENDER::Render3DDX10::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_INDEXBUFFER, GAIA::RENDER::Render3DDX11::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_INDEXBUFFER, GAIA::RENDER::Render3DGL1::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_INDEXBUFFER, GAIA::RENDER::Render3DGL2::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_INDEXBUFFER, GAIA::RENDER::Render3DGL3::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_INDEXBUFFER, GAIA::RENDER::Render3DGLES1::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_INDEXBUFFER, GAIA::RENDER::Render3DGLES2::IndexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_INDEXBUFFER, GAIA::RENDER::Render3DGLES3::IndexBuffer);

			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_VERTEXBUFFER, GAIA::RENDER::Render3DDX9::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_VERTEXBUFFER, GAIA::RENDER::Render3DDX10::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_VERTEXBUFFER, GAIA::RENDER::Render3DDX11::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_VERTEXBUFFER, GAIA::RENDER::Render3DGL1::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_VERTEXBUFFER, GAIA::RENDER::Render3DGL2::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_VERTEXBUFFER, GAIA::RENDER::Render3DGL3::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_VERTEXBUFFER, GAIA::RENDER::Render3DGLES1::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_VERTEXBUFFER, GAIA::RENDER::Render3DGLES2::VertexBuffer);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_VERTEXBUFFER, GAIA::RENDER::Render3DGLES3::VertexBuffer);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_CONTEXT, GAIA::RENDER::Render2DDDraw::Context);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_CONTEXT, GAIA::RENDER::Render2DGDIPlus::Context);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_CONTEXT, GAIA::RENDER::Render3DDX9::Context);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_CONTEXT, GAIA::RENDER::Render3DDX10::Context);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_CONTEXT, GAIA::RENDER::Render3DDX11::Context);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_CONTEXT, GAIA::RENDER::Render3DGL1::Context);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_CONTEXT, GAIA::RENDER::Render3DGL2::Context);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_CONTEXT, GAIA::RENDER::Render3DGL3::Context);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_CONTEXT, GAIA::RENDER::Render3DGLES1::Context);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_CONTEXT, GAIA::RENDER::Render3DGLES2::Context);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_CONTEXT, GAIA::RENDER::Render3DGLES3::Context);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_TEXTUREFETCHDATA, GAIA::RENDER::Render2DDDraw::Texture::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_TEXTUREFETCHDATA, GAIA::RENDER::Render2DGDIPlus::Texture::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_TEXTUREFETCHDATA, GAIA::RENDER::Render3DDX9::Texture::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_TEXTUREFETCHDATA, GAIA::RENDER::Render3DDX10::Texture::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_TEXTUREFETCHDATA, GAIA::RENDER::Render3DDX11::Texture::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_TEXTUREFETCHDATA, GAIA::RENDER::Render3DGL1::Texture::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_TEXTUREFETCHDATA, GAIA::RENDER::Render3DGL2::Texture::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_TEXTUREFETCHDATA, GAIA::RENDER::Render3DGL3::Texture::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_TEXTUREFETCHDATA, GAIA::RENDER::Render3DGLES1::Texture::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_TEXTUREFETCHDATA, GAIA::RENDER::Render3DGLES2::Texture::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_TEXTUREFETCHDATA, GAIA::RENDER::Render3DGLES3::Texture::FetchData);

			GAIA_INSTCREATOR(CLSID_RENDER_2D_DDRAW_TARGETFETCHDATA, GAIA::RENDER::Render2DDDraw::Target::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_2D_GDIPLUS_TARGETFETCHDATA, GAIA::RENDER::Render2DGDIPlus::Target::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_TARGETFETCHDATA, GAIA::RENDER::Render3DDX9::Target::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_TARGETFETCHDATA, GAIA::RENDER::Render3DDX10::Target::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_TARGETFETCHDATA, GAIA::RENDER::Render3DDX11::Target::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_TARGETFETCHDATA, GAIA::RENDER::Render3DGL1::Target::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_TARGETFETCHDATA, GAIA::RENDER::Render3DGL2::Target::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_TARGETFETCHDATA, GAIA::RENDER::Render3DGL3::Target::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_TARGETFETCHDATA, GAIA::RENDER::Render3DGLES1::Target::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_TARGETFETCHDATA, GAIA::RENDER::Render3DGLES2::Target::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_TARGETFETCHDATA, GAIA::RENDER::Render3DGLES3::Target::FetchData);

			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_VERTEXBUFFERFETCHDATA, GAIA::RENDER::Render3DDX9::VertexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_VERTEXBUFFERFETCHDATA, GAIA::RENDER::Render3DDX10::VertexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_VERTEXBUFFERFETCHDATA, GAIA::RENDER::Render3DDX11::VertexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_VERTEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGL1::VertexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_VERTEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGL2::VertexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_VERTEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGL3::VertexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_VERTEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGLES1::VertexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_VERTEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGLES2::VertexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_VERTEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGLES3::VertexBuffer::FetchData);

			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX9_INDEXBUFFERFETCHDATA, GAIA::RENDER::Render3DDX9::IndexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX10_INDEXBUFFERFETCHDATA, GAIA::RENDER::Render3DDX10::IndexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_DX11_INDEXBUFFERFETCHDATA, GAIA::RENDER::Render3DDX11::IndexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL1_INDEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGL1::IndexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL2_INDEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGL2::IndexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GL3_INDEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGL3::IndexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES1_INDEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGLES1::IndexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES2_INDEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGLES2::IndexBuffer::FetchData);
			GAIA_INSTCREATOR(CLSID_RENDER_3D_GLES3_INDEXBUFFERFETCHDATA, GAIA::RENDER::Render3DGLES3::IndexBuffer::FetchData);
		};
	};
};

#endif