#ifndef		__GAIA_FRAMEWORK_INSTANCE_CREATOR_IMPL_H__
#define		__GAIA_FRAMEWORK_INSTANCE_CREATOR_IMPL_H__

namespace GAIA
{
	namespace FWORK
	{
		namespace INSTCREATOR
		{
		#define GAIA_INSTCREATOR(cid, type) static GAIA::FWORK::Instance* cid##_PROC(){return new type;}

			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_GATEWAYMEM, GAIA::DATATRAFFIC::GatewayMem)
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_GATEWAYSHAREMEM, GAIA::DATATRAFFIC::GatewayShareMem)
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_GATEWAYFILE, GAIA::DATATRAFFIC::GatewayFile)
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_ROUTEMEM, GAIA::DATATRAFFIC::RouteMem)
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_ROUTENET, GAIA::DATATRAFFIC::RouteNet)
			GAIA_INSTCREATOR(CLSID_DATATRAFFIC_TRANSMISSIONIDM, GAIA::DATATRAFFIC::TransmissionIDM)

			GAIA_INSTCREATOR(CLSID_IO_FILEIO, GAIA::IO::FileIO)
			GAIA_INSTCREATOR(CLSID_IO_MEMIO, GAIA::IO::MemIO)
			GAIA_INSTCREATOR(CLSID_IO_SCREENIO, GAIA::IO::ScreenIO)

			GAIA_INSTCREATOR(CLSID_SERIALIZER, GAIA::SERIALIZER::Serializer)

			GAIA_INSTCREATOR(CLSID_UI_CANVAS, GAIA::UI::Canvas)
			GAIA_INSTCREATOR(CLSID_UI_PAINTER, GAIA::UI::Painter)
			GAIA_INSTCREATOR(CLSID_UI_FORM, GAIA::UI::Form)
			GAIA_INSTCREATOR(CLSID_UI_PUSHBUTTON, GAIA::UI::PushButton)
			GAIA_INSTCREATOR(CLSID_UI_RADIOBUTTON, GAIA::UI::RadioButton)
			GAIA_INSTCREATOR(CLSID_UI_CHECKBUTTON, GAIA::UI::CheckButton)
			GAIA_INSTCREATOR(CLSID_UI_LABEL, GAIA::UI::Label)
			GAIA_INSTCREATOR(CLSID_UI_EDIT, GAIA::UI::Edit)
			GAIA_INSTCREATOR(CLSID_UI_DOCUMENT, GAIA::UI::Document)
			GAIA_INSTCREATOR(CLSID_UI_PROGRESSBAR, GAIA::UI::ProgressBar)

			GAIA_INSTCREATOR(CLSID_STATE_STATE, GAIA::STATE::State)
			GAIA_INSTCREATOR(CLSID_STATE_STATECTN, GAIA::STATE::StateCtn)
			GAIA_INSTCREATOR(CLSID_STATE_STATEMGR, GAIA::STATE::StateMgr)

			GAIA_INSTCREATOR(CLSID_TIMER_TIMER, GAIA::TIMER::Timer)
			GAIA_INSTCREATOR(CLSID_TIMER_TIMERMGR, GAIA::TIMER::TimerMgr)
		};
	};
};

#endif